### ISSUE TITLE
This project has no license

### ISSUE THREAD

**Issue by Ana06** [openSUSE/obs-scrum#12]
This project has no license. 😭 😭  I know that we do not have many things here, but still it would be nice to have a license. In this project there is no code at all, so we need a content license. I would suggest using a [Creative Commons Attribution 4.0](https://choosealicense.com/licenses/cc-by-4.0).

I would like that we change it, and for this to happens we need the agreement of **all** the contributors to this project, as there are no many contributors here, this may be possible. 😉

@bot-bs is myself, so it is also fine with the change. 😉 

@bgeuken, @DavidKang, @ChrisBr, @eduardoj and @mdeniz what do you think?

**Comment by eduardoj** [comment]
I agree with applying a Creative Commons Attribution 4.0 license.

**Comment by bgeuken** [comment]
Sure, fine with me.

**Comment by DavidKang** [comment]
I agree 😸

**Comment by Ana06** [comment]
@ChrisBr, @mdeniz ^^

**Comment by ChrisBr** [comment]
LGTM

**Comment by mdeniz** [comment]
I agree!
